#!/usr/bin/env python3
"""Paper 21 v2.0 reproducibility script 08.

Purpose:
    Validate all frozen JSON outputs shipped in the Paper 21 v2.0 public
    reproducibility bundle.

Inputs:
    results/*.json generated by scripts 01-07.

Outputs:
    PASS/FAIL lines and a final summary.

External dependencies:
    Python standard library only.

Claim boundary:
    Fast arithmetic/provenance validation of the public bundle outputs.
"""

from __future__ import annotations

import json
import math
from pathlib import Path


BUNDLE_ROOT = Path(__file__).resolve().parents[1]
RESULTS = BUNDLE_ROOT / "results"

CHECKS = [
    ("r4_firas_dependency_audit_results.json", ("R4_FIRAS",), 1.0031014644, 1e-12),
    ("r4_firas_dependency_audit_results.json", ("active_T_obs_K",), 2.725499012374763, 1e-12),
    ("r4_firas_dependency_audit_results.json", ("R4_enters_active_BBN_scorecard",), False, 0),
    ("L1_puncture_load_results.json", ("L_1",), 0.22416889162576648, 1e-14),
    ("L2_puncture_load_results.json", ("L_2",), 0.13805247907094412, 1e-14),
    ("ac1_closure_results.json", ("factors", "J_theta_degree1"), 0.8339461798286282, 1e-14),
    ("ac1_closure_results.json", ("factors", "J_theta_degree1_rel_error_pct_vs_strict_ratio"), 0.4294211437022577, 1e-12),
    ("prymordial_wrapper_conventions_results.json", ("helium_observational_output", "PRyMresults_index"), 3, 0),
    ("bbn_scorecard_results.json", ("scorecard", "Y_p_sigma"), 0.7045360432106975, 1e-12),
    ("bbn_scorecard_results.json", ("scorecard", "D_over_H_sigma"), -0.5529801681809717, 1e-12),
    ("bbn_scorecard_results.json", ("scorecard", "Li7_over_H_sigma"), 12.204309073285641, 1e-12),
    ("bbn_scorecard_results.json", ("scorecard", "chi2_DH_plus_Yp"), 0.8021581025844415, 1e-12),
    ("operator_algebra_live_theorem_artifacts_results.json", ("consistency_checks", "local_nontraciality_trace_equals_one"), True, 0),
    ("operator_algebra_live_theorem_artifacts_results.json", ("consistency_checks", "T_obs_formula_matches_imported_value"), True, 0),
    ("operator_algebra_live_theorem_artifacts_results.json", ("consistency_checks", "R4_does_not_enter_active_BBN_scorecard"), True, 0),
    ("operator_algebra_live_theorem_artifacts_results.json", ("consistency_checks", "rank2_allows_j_3_over_2"), True, 0)
]


def descend(payload, path):
    cur = payload
    for key in path:
        cur = cur[key]
    return cur


def matches(actual, expected, tolerance) -> bool:
    if isinstance(expected, bool):
        return actual is expected
    if isinstance(expected, int):
        return int(actual) == expected
    return math.isclose(float(actual), float(expected), rel_tol=0.0, abs_tol=tolerance)


def main() -> int:
    pass_count = 0
    failures = []
    for filename, path, expected, tolerance in CHECKS:
        payload = json.loads((RESULTS / filename).read_text())
        actual = descend(payload, path)
        ok = matches(actual, expected, tolerance)
        if ok:
            pass_count += 1
            print(f"PASS {filename} {'.'.join(map(str, path))}")
        else:
            delta = None if isinstance(expected, bool) else float(actual) - float(expected)
            failures.append({
                "file": filename,
                "path": path,
                "actual": actual,
                "expected": expected,
                "tolerance": tolerance,
                "delta": delta
            })
            print(f"FAIL {filename} {'.'.join(map(str, path))}: actual={actual!r} expected={expected!r}")
    fail_count = len(failures)
    print(f"SUMMARY total_checks={len(CHECKS)} pass_count={pass_count} fail_count={fail_count}")
    if failures:
        print(json.dumps({"failures": failures}, indent=2, sort_keys=True))
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
