#!/usr/bin/env python3
"""Paper 35 v2.0 script 09: R4/FIRAS impact audit.

Purpose:
    Record the blast radius of replacing the retired implicit optical readout
    normalization R4=1 with the Paper 17 v1.5 FIRAS-fixed value

        R4_FIRAS = 1.0031014644105183.

    Paper 35 is impacted because its late-time eta route uses the observer
    photon bath temperature T_obs.  The local BBN temperature route uses T_IO
    and is invariant when recomputed consistently.

Inputs:
    data/imported_constants.json
    results/*.json generated by scripts 01-08

Outputs:
    results/r4_firas_impact_audit_results.json

Claim boundary:
    VERIFIED impact ledger.  The structural kappa-audit conclusions are in
    reports/paper35_v12_r4_firas_kappa_audit_report.md.
"""

from __future__ import annotations

import json
import math
from pathlib import Path


BUNDLE_ROOT = Path(__file__).resolve().parents[1]
DATA_PATH = BUNDLE_ROOT / "data" / "imported_constants.json"
RESULTS = BUNDLE_ROOT / "results"
RESULTS_PATH = RESULTS / "r4_firas_impact_audit_results.json"


OLD_V1_1 = {
    "T_obs_R4_equals_1_K": 2.7253048490552736,
    "temperature_conversion_factor": 1.071240943860573,
    "eta_late_mean_baryon_mass": 5.748778515173695e-10,
    "eta_late_proton_mass": 5.74179586430453e-10,
    "Y_B_target": 8.165878572689907e-11,
    "eps1_kappa_target": 5.905280726708112e-08,
    "T_f_target_GeV": 2.20039385974778e13,
    "jwst_z10_ratio": 1.478575721721601,
    "jwst_jades_z14_delta_myr": 135.78694162866518,
}


def load_json(path: Path) -> dict:
    return json.loads(path.read_text())


def rel_shift(new: float, old: float) -> float:
    return (new / old) - 1.0


def main() -> int:
    constants = load_json(DATA_PATH)
    fw = constants["framework_constants"]
    eta = constants["eta_inputs"]
    eta_results = load_json(RESULTS / "eta_derivation_chain_results.json")
    temp_results = load_json(RESULTS / "temperature_assignment_results.json")
    lep_results = load_json(RESULTS / "leptogenesis_target_reduction_results.json")
    jwst_results = load_json(RESULTS / "jwst_formation_time_table_results.json")

    gamma = fw["gamma_BI"]
    k_gauge = math.log(1.0 + gamma**2)
    x_r4_source = fw["x_R4_source"]
    r4_firas = fw["R4_FIRAS"]
    t_io = eta["T_IO_K"]
    t_firas = eta["T_FIRAS_K"]
    t_obs_firas = t_io * x_r4_source ** (r4_firas * k_gauge)
    r4_from_firas = math.log(t_firas / t_io) / (k_gauge * math.log(x_r4_source))

    new_eta_mean = eta_results["headline"]["eta_late_mean_baryon_mass"]
    new_eta_proton = eta_results["headline"]["eta_late_proton_mass"]
    new_conversion = temp_results["numbers"]["temperature_conversion_factor_direct"]
    new_eta_bbn = temp_results["numbers"]["eta_BBN_proton_mass"]
    new_yb = lep_results["numbers"]["Y_B_target"]
    new_eps = lep_results["numbers"]["eps1_kappa_target"]
    new_t_f_target = lep_results["numbers"]["T_f_poplawski_eta_target_GeV"]
    new_z10_ratio = jwst_results["grid"][0]["ratio"]
    new_jades_delta = jwst_results["objects"][0]["delta_myr"]

    results = {
        "paper": constants["paper"],
        "classification": "verified / R4-FIRAS impact audit",
        "verdict": {
            "cmb_temperature_prediction_present": False,
            "R4_used_by_eta_late": True,
            "R4_used_by_eta_BBN": False,
            "eta_BBN_changed_when_recomputed_consistently": False,
            "DESI_changed": False,
            "dark_matter_null_changed": False,
        },
        "R4_FIRAS": {
            "value": r4_firas,
            "recomputed_from_FIRAS": r4_from_firas,
            "sigma_FIRAS_only": fw["sigma_R4_FIRAS_only"],
            "T_IO_K": t_io,
            "T_FIRAS_K": t_firas,
            "T_obs_FIRAS_fixed_K": t_obs_firas,
            "T_obs_R4_equals_1_K_historical": eta["T_obs_R4_equals_1_K_historical"],
            "readout_formula": "T_obs(R4) = T_IO * x_R4_source^(R4*K_gauge)",
            "claim_boundary": "FIRAS-fixed empirical observer-side thermal datum; not an independent CMB-temperature prediction",
        },
        "numeric_impacts": {
            "T_obs_K": {
                "old_R4_equals_1": OLD_V1_1["T_obs_R4_equals_1_K"],
                "new_R4_FIRAS": t_obs_firas,
                "delta": t_obs_firas - OLD_V1_1["T_obs_R4_equals_1_K"],
                "relative_shift": rel_shift(t_obs_firas, OLD_V1_1["T_obs_R4_equals_1_K"]),
            },
            "temperature_conversion_factor": {
                "old_R4_equals_1": OLD_V1_1["temperature_conversion_factor"],
                "new_R4_FIRAS": new_conversion,
                "relative_shift": rel_shift(new_conversion, OLD_V1_1["temperature_conversion_factor"]),
            },
            "eta_late_mean_baryon_mass": {
                "old_R4_equals_1": OLD_V1_1["eta_late_mean_baryon_mass"],
                "new_R4_FIRAS": new_eta_mean,
                "relative_shift": rel_shift(new_eta_mean, OLD_V1_1["eta_late_mean_baryon_mass"]),
            },
            "eta_late_proton_mass": {
                "old_R4_equals_1": OLD_V1_1["eta_late_proton_mass"],
                "new_R4_FIRAS": new_eta_proton,
                "relative_shift": rel_shift(new_eta_proton, OLD_V1_1["eta_late_proton_mass"]),
            },
            "eta_BBN_proton_mass": {
                "old_R4_equals_1": constants["eta_inputs"]["eta_BBN_proton_mass"],
                "new_R4_FIRAS": new_eta_bbn,
                "relative_shift": rel_shift(new_eta_bbn, constants["eta_inputs"]["eta_BBN_proton_mass"]),
                "reason_invariant": "eta_late(T_obs) * (T_obs/T_IO)^3 reduces to the local T_IO photon-density calculation.",
            },
            "Y_B_target": {
                "old_R4_equals_1": OLD_V1_1["Y_B_target"],
                "new_R4_FIRAS": new_yb,
                "relative_shift": rel_shift(new_yb, OLD_V1_1["Y_B_target"]),
            },
            "eps1_kappa_target": {
                "old_R4_equals_1": OLD_V1_1["eps1_kappa_target"],
                "new_R4_FIRAS": new_eps,
                "relative_shift": rel_shift(new_eps, OLD_V1_1["eps1_kappa_target"]),
            },
            "T_f_poplawski_eta_target_GeV": {
                "old_R4_equals_1": OLD_V1_1["T_f_target_GeV"],
                "new_R4_FIRAS": new_t_f_target,
                "relative_shift": rel_shift(new_t_f_target, OLD_V1_1["T_f_target_GeV"]),
                "note": "The chiral diagnostic T_f is unchanged; this entry is the eta-derived external target-compatibility scale.",
            },
            "jwst_z10_ratio": {
                "old_T_cmb_2p7253": OLD_V1_1["jwst_z10_ratio"],
                "new_FIRAS_T_cmb": new_z10_ratio,
                "relative_shift": rel_shift(new_z10_ratio, OLD_V1_1["jwst_z10_ratio"]),
            },
            "jwst_jades_z14_delta_myr": {
                "old_T_cmb_2p7253": OLD_V1_1["jwst_jades_z14_delta_myr"],
                "new_FIRAS_T_cmb": new_jades_delta,
                "delta_myr": new_jades_delta - OLD_V1_1["jwst_jades_z14_delta_myr"],
            },
        },
        "script_impacts": [
            {
                "script": "01_eta_derivation_chain.py",
                "r4_damage_status": "impacted_and_repaired",
                "reason": "Late-time eta uses observer photon bath T_obs; v1.2 uses FIRAS-fixed R4 instead of implicit R4=1.",
            },
            {
                "script": "02_temperature_assignment.py",
                "r4_damage_status": "impacted_and_repaired",
                "reason": "Conversion factor changes to x_R4_source^(3 R4_FIRAS K_gauge); eta_BBN remains invariant after consistent recomputation.",
            },
            {
                "script": "03_chiral_source_diagnostic.py",
                "r4_damage_status": "not_impacted",
                "reason": "Uses K_gauge powers and diagnostic Planck scale only.",
            },
            {
                "script": "04_leptogenesis_target_reduction.py",
                "r4_damage_status": "impacted_and_repaired",
                "reason": "Uses eta_late as target input; the target shifts with FIRAS-fixed T_obs.",
            },
            {
                "script": "05_baryogenesis_registry_summary.py",
                "r4_damage_status": "registry_counts_not_impacted",
                "reason": "The 48-surface CLEAN/CONDITIONAL_VERIFIED counts do not depend on the eta numerical shift.",
            },
            {
                "script": "06_jwst_formation_time_table.py",
                "r4_damage_status": "minor_input_hygiene",
                "reason": "Radiation-density T_cmb input now uses FIRAS empirical temperature rather than retired 2.7253 shorthand.",
            },
            {
                "script": "07_desi_confrontation.py",
                "r4_damage_status": "not_impacted",
                "reason": "Uses late-time DESI BAO branch parameters; no optical thermal readout.",
            },
            {
                "script": "08_dark_matter_null_forecast.py",
                "r4_damage_status": "not_impacted",
                "reason": "Uses f_b=2 gamma/x and direct-detection limit checks only.",
            },
            {
                "script": "10_validate_expected_outputs.py",
                "r4_damage_status": "impacted_and_repaired",
                "reason": "Expected outputs updated to v1.2 FIRAS-fixed values.",
            },
        ],
    }

    RESULTS_PATH.write_text(json.dumps(results, indent=2, sort_keys=True) + "\n")
    print(json.dumps({"state": "wrote", "path": str(RESULTS_PATH)}, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
