#!/usr/bin/env python3
"""
Paper 24 v2.3 reproducibility script 02.

Purpose:
    Recompute the imported excited-state response used in Paper 24 v2.3. The
    script verifies the Henderson B(E2) spin-multiplicity conversion, projects
    the imported transition strength through the Paper 24 amplitude-weighted
    Coulomb kernel, and reruns the branch response through the Paper 24 BBN
    scorecard helper.

Inputs:
    - results/final_excited_branch_results.json, generated by script 03 or
      supplied as a frozen bundle output.
    - Source values hard-coded below from the cited primary sources.

Outputs:
    - results/excited_state_import_recomputation_results.json
    - reports/excited_state_import_recomputation_memo.md

External dependencies:
    - scripts/03_run_final_bbn_scorecard.py
    - PRyMordial indirectly, when the imported scorecard is rerun.

Claim boundary:
    - verified: Henderson arithmetic, detailed-balance spin factor, TUNL/Li-7
      mirror checks, and frozen output validation.
    - conditional: mapping sqrt(B(E2)) through the Paper 24 branch-dressing
      scale.
    - not used as theorem evidence: reconstructed AZURE2/R-matrix scaffolds.

Run:
    python3 scripts/03_run_final_bbn_scorecard.py
    python3 scripts/02_recompute_excited_state_import.py
"""
from __future__ import annotations

import importlib.util
import json
import math
import time
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any


BUNDLE_ROOT = Path(__file__).resolve().parents[1]
PAPER24 = BUNDLE_ROOT
OUT_JSON = PAPER24 / "results" / "excited_state_import_recomputation_results.json"
OUT_MEMO = PAPER24 / "reports" / "excited_state_import_recomputation_memo.md"

P24_SCRIPT = BUNDLE_ROOT / "scripts" / "03_run_final_bbn_scorecard.py"
P24_RESULTS = BUNDLE_ROOT / "results" / "final_excited_branch_results.json"

CLASSIFICATION = "verified / recomputation / PAPER24_V22_EXCITED_STATE_IMPORT"

# Source values verified against the source documents cited in the memo.
HENDERSON_BE7_B_E2_UP = 26.0
HENDERSON_BE7_B_E2_STAT = 6.0
HENDERSON_BE7_B_E2_SYS = 3.0
TUNL_BE7_TAU_FS = 192.0
TUNL_BE7_TAU_SIGMA_FS = 25.0
TUNL_LI7_B_E2_UP = 8.3
TUNL_LI7_B_E2_UP_SIGMA = 0.5
TUNL_LI7_C2_GAMMA_WIDTH_EV = 2.8e-7
TUNL_LI7_C2_GAMMA_WIDTH_SIGMA_EV = 1.6e-7

E_GAMMA_BE7_MEV = 0.42920
E_GAMMA_LI7_MEV = 0.4776
HBAR_EV_S = 6.582119569e-16
E2_RATE_COEFF = 1.2239e9  # s^-1 MeV^-5 (e^2 fm^4)^-1


@dataclass
class ImportCase:
    label: str
    claim_status: str
    B_E2_used_e2fm4: float
    B_E2_sigma_e2fm4: float | None
    B_E2_convention: str
    q_scale_b: float
    q_scale_sigma_b: float | None
    q_trans_ex_b: float
    q_trans_ex_sigma_b: float | None
    R_ex_T9eff: float
    R_ex_T9eff_from_B_plus_1sigma: float | None
    R_ex_T9eff_from_B_minus_1sigma: float | None
    R_34_tot_T9eff: float
    R_34_tot_T9eff_from_B_plus_1sigma: float | None
    R_34_tot_T9eff_from_B_minus_1sigma: float | None
    Li7_H: float
    Li7_sigma: float
    D_H: float
    D_H_sigma: float
    Y_p: float
    Y_p_sigma: float


def ts() -> str:
    return time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())


def load_p24_module():
    """Load the sibling scorecard script as a module without importing lab code."""

    spec = importlib.util.spec_from_file_location("paper24_final_push_excited_branch_v22_import", P24_SCRIPT)
    module = importlib.util.module_from_spec(spec)
    assert spec.loader is not None
    spec.loader.exec_module(module)
    return module


def combined_sigma(*parts: float) -> float:
    """Quadrature combination of independent uncertainty components."""

    return math.sqrt(sum(part * part for part in parts))


def q_scale_from_b_e2(B_e2: float) -> float:
    """Convert sqrt(B(E2)) from e fm^2 to a quadrupole scale in barns."""

    # sqrt(e^2 fm^4) -> e fm^2; 1 barn = 100 fm^2.
    return math.sqrt(B_e2) / 100.0


def q_scale_sigma_from_b_e2(B_e2: float, sigma: float) -> float:
    return sigma / (200.0 * math.sqrt(B_e2))


def b_down_from_b_up(B_up: float, J_up_initial: float, J_down_initial: float) -> float:
    """Detailed balance: (2Ji+1) B(i->f) = (2Jf+1) B(f->i)."""

    # Henderson reports the upward 3/2- -> 1/2- value. Paper 24 v2.3 needs the
    # de-excitation 1/2- -> 3/2- strength for the excited-state response.
    return ((2.0 * J_up_initial + 1.0) / (2.0 * J_down_initial + 1.0)) * B_up


def b_sigma_down_from_b_up(sigma_up: float, J_up_initial: float, J_down_initial: float) -> float:
    return ((2.0 * J_up_initial + 1.0) / (2.0 * J_down_initial + 1.0)) * sigma_up


def e2_rate(E_gamma_mev: float, B_e2_down: float) -> float:
    """Standard E2 gamma-decay rate from E_gamma and B(E2 down)."""

    return E2_RATE_COEFF * (E_gamma_mev ** 5) * B_e2_down


def gamma_width_from_rate(rate_s: float) -> float:
    return HBAR_EV_S * rate_s


def b_e2_down_from_gamma_width(E_gamma_mev: float, gamma_width_ev: float) -> float:
    return (gamma_width_ev / HBAR_EV_S) / (E2_RATE_COEFF * (E_gamma_mev ** 5))


def make_import_case(
    p24: Any,
    label: str,
    claim_status: str,
    B_e2: float,
    B_sigma: float | None,
    convention: str,
    amp_weighted_f0: float,
    T9_eff: float,
) -> ImportCase:
    """Build one imported-response case and pass it through the scorecard."""

    # Imported transition-amplitude scale:
    # q_trans = sqrt(B(E2)) / 100 * <F0>_amp,ex.
    q_scale = q_scale_from_b_e2(B_e2)
    q_scale_sigma = q_scale_sigma_from_b_e2(B_e2, B_sigma) if B_sigma is not None else None
    q_trans = q_scale * amp_weighted_f0
    q_trans_sigma = q_scale_sigma * amp_weighted_f0 if q_scale_sigma is not None else None
    r_ex_plus = None
    r_ex_minus = None
    r_tot_plus = None
    r_tot_minus = None
    if B_sigma is not None:
        # Propagate one-sigma B(E2) endpoints through the nonlinear R_ex map.
        B_plus = max(B_e2 + B_sigma, 1e-12)
        B_minus = max(B_e2 - B_sigma, 1e-12)
        q_plus = q_scale_from_b_e2(B_plus) * amp_weighted_f0
        q_minus = q_scale_from_b_e2(B_minus) * amp_weighted_f0
        r_ex_plus = p24.R_ex(T9_eff, q_plus)
        r_ex_minus = p24.R_ex(T9_eff, q_minus)
        r_tot_plus = p24.R34_total(T9_eff, q_plus)
        r_tot_minus = p24.R34_total(T9_eff, q_minus)
    network = p24.run_network_case(label, q_trans)
    return ImportCase(
        label=label,
        claim_status=claim_status,
        B_E2_used_e2fm4=B_e2,
        B_E2_sigma_e2fm4=B_sigma,
        B_E2_convention=convention,
        q_scale_b=q_scale,
        q_scale_sigma_b=q_scale_sigma,
        q_trans_ex_b=q_trans,
        q_trans_ex_sigma_b=q_trans_sigma,
        R_ex_T9eff=p24.R_ex(T9_eff, q_trans),
        R_ex_T9eff_from_B_plus_1sigma=r_ex_plus,
        R_ex_T9eff_from_B_minus_1sigma=r_ex_minus,
        R_34_tot_T9eff=p24.R34_total(T9_eff, q_trans),
        R_34_tot_T9eff_from_B_plus_1sigma=r_tot_plus,
        R_34_tot_T9eff_from_B_minus_1sigma=r_tot_minus,
        Li7_H=network.Li7_H,
        Li7_sigma=network.Li7_sigma,
        D_H=network.D_H,
        D_H_sigma=network.D_H_sigma,
        Y_p=network.Y_p,
        Y_p_sigma=network.Y_p_sigma,
    )


def compute() -> dict[str, Any]:
    """Compute all Paper 24 v2.3 imported-response cases."""

    p24 = load_p24_module()
    p24_payload = json.loads(P24_RESULTS.read_text())
    amp_weighted_f0 = float(p24_payload["kernel_excited_state"]["amp_weighted_avg_F0"])
    T9_eff = float(p24_payload["constants"]["T9_eff"])
    v21_q_trans = float(p24_payload["kernel_excited_state"]["Q_trans_from_amp_weighted_avg_b"])

    # Henderson uncertainty is quoted as statistical and systematic pieces.
    b_up_sigma = combined_sigma(HENDERSON_BE7_B_E2_STAT, HENDERSON_BE7_B_E2_SYS)
    b_down = b_down_from_b_up(HENDERSON_BE7_B_E2_UP, J_up_initial=1.5, J_down_initial=0.5)
    b_down_sigma = b_sigma_down_from_b_up(b_up_sigma, J_up_initial=1.5, J_down_initial=0.5)
    b_half_rejected = 0.5 * HENDERSON_BE7_B_E2_UP

    cases = [
        make_import_case(
            p24,
            "henderson_be7_deexcitation_down_corrected",
            "verified_import_primary_for_excited_state_response",
            b_down,
            b_down_sigma,
            "B(E2; 1/2- -> 3/2-) from detailed balance, factor 2 times Henderson upward value",
            amp_weighted_f0,
            T9_eff,
        ),
        make_import_case(
            p24,
            "henderson_be7_published_upward_convention",
            "verified_import_crosscheck",
            HENDERSON_BE7_B_E2_UP,
            b_up_sigma,
            "published B(E2; 3/2- -> 1/2-) Coulomb-excitation convention",
            amp_weighted_f0,
            T9_eff,
        ),
        make_import_case(
            p24,
            "gemini_half_factor_rejected_diagnostic",
            "rejected_diagnostic_not_load_bearing",
            b_half_rejected,
            0.5 * b_up_sigma,
            "incorrect half-factor convention; retained only to document rejection of Gemini numeric",
            amp_weighted_f0,
            T9_eff,
        ),
    ]

    paper24_v21 = {
        "R_ex_stated_for_comparison": 0.666,
        "q_trans_ex_amp_weighted_b": v21_q_trans,
        "R_ex_T9eff_from_old_q_trans": p24.R_ex(T9_eff, v21_q_trans),
        "R_34_tot_T9eff_from_old_q_trans": p24.R34_total(T9_eff, v21_q_trans),
    }

    tau_s = TUNL_BE7_TAU_FS * 1e-15
    lambda_total = 1.0 / tau_s
    gamma_total_ev = gamma_width_from_rate(lambda_total)
    henderson_e2_rate = e2_rate(E_GAMMA_BE7_MEV, b_down)
    henderson_e2_width_ev = gamma_width_from_rate(henderson_e2_rate)
    henderson_e2_fraction_of_tunl_total = henderson_e2_rate / lambda_total
    b_all_e2_down = b_e2_down_from_gamma_width(E_GAMMA_BE7_MEV, gamma_total_ev)

    li7_c2_b_down = b_e2_down_from_gamma_width(E_GAMMA_LI7_MEV, TUNL_LI7_C2_GAMMA_WIDTH_EV)
    li7_c2_b_down_sigma = b_e2_down_from_gamma_width(E_GAMMA_LI7_MEV, TUNL_LI7_C2_GAMMA_WIDTH_SIGMA_EV)
    li7_c2_b_up = 0.5 * li7_c2_b_down
    li7_c2_b_up_sigma = 0.5 * li7_c2_b_down_sigma
    henderson_ratio_to_tunl_li_up = HENDERSON_BE7_B_E2_UP / TUNL_LI7_B_E2_UP
    henderson_ratio_sigma = henderson_ratio_to_tunl_li_up * math.sqrt(
        (b_up_sigma / HENDERSON_BE7_B_E2_UP) ** 2
        + (TUNL_LI7_B_E2_UP_SIGMA / TUNL_LI7_B_E2_UP) ** 2
    )

    primary = cases[0]
    outcome = {
        "classification": (
            "B: imported excited-state response differs from the exact stated R_ex=0.666 central value, "
            "but the corrected Henderson de-excitation convention reproduces the old quadrupole scale "
            "closely and the PRyMordial Li7/H result remains in the same observational band."
        ),
        "preferred_case": primary.label,
        "preferred_Li7_H": primary.Li7_H,
        "preferred_Li7_sigma": primary.Li7_sigma,
        "unchanged_headline_allowed": False,
        "headline_guidance": (
            "Do not claim the central value is literally unchanged. v2.3 can claim the imported "
            "primary-source response preserves the lithium solution within the source/convention band."
        ),
    }

    payload = {
        "classification": CLASSIFICATION,
        "state": "completed",
        "updated_at": ts(),
        "source_values": {
            "henderson_2019": {
                "B_E2_up_e2fm4": HENDERSON_BE7_B_E2_UP,
                "stat_sigma": HENDERSON_BE7_B_E2_STAT,
                "sys_sigma": HENDERSON_BE7_B_E2_SYS,
                "combined_sigma": b_up_sigma,
                "B_E2_down_corrected_e2fm4": b_down,
                "B_E2_down_corrected_sigma": b_down_sigma,
                "spin_multiplicity_check": (
                    "Detailed balance gives B_down = 2 * B_up for 1/2- -> 3/2-. "
                    "The proposed 13 e^2 fm^4 half-factor is rejected."
                ),
            },
            "lichtenstadt_tunl_mirror_crosscheck": {
                "li7_evaluated_B_E2_up_e2fm4": TUNL_LI7_B_E2_UP,
                "li7_evaluated_B_E2_up_sigma": TUNL_LI7_B_E2_UP_SIGMA,
                "li7_c2_gamma_width_ev": TUNL_LI7_C2_GAMMA_WIDTH_EV,
                "li7_c2_gamma_width_sigma_ev": TUNL_LI7_C2_GAMMA_WIDTH_SIGMA_EV,
                "li7_c2_inferred_B_E2_down_e2fm4": li7_c2_b_down,
                "li7_c2_inferred_B_E2_down_sigma": li7_c2_b_down_sigma,
                "li7_c2_inferred_B_E2_up_e2fm4": li7_c2_b_up,
                "li7_c2_inferred_B_E2_up_sigma": li7_c2_b_up_sigma,
                "be7_to_li7_evaluated_up_ratio": henderson_ratio_to_tunl_li_up,
                "be7_to_li7_evaluated_up_ratio_sigma": henderson_ratio_sigma,
            },
            "tunl_lifetime_crosscheck": {
                "tau_fs": TUNL_BE7_TAU_FS,
                "tau_sigma_fs": TUNL_BE7_TAU_SIGMA_FS,
                "total_gamma_width_ev": gamma_total_ev,
                "henderson_E2_partial_width_ev": henderson_e2_width_ev,
                "henderson_E2_fraction_of_total_width": henderson_e2_fraction_of_tunl_total,
                "all_E2_B_E2_down_upper_bound_e2fm4": b_all_e2_down,
                "read": (
                    "The lifetime is M1 dominated and does not by itself determine R_ex. "
                    "It is a consistency check that the Henderson E2 partial width is tiny."
                ),
            },
            "odell_2022": {
                "used_for_R_ex": False,
                "read": (
                    "Odell/BRICK constrains ANCs and capture/scattering extrapolations, but without "
                    "author-verified deck/posterior data it is not used as an authoritative R_ex import."
                ),
            },
        },
        "paper24_model_inputs": {
            "amp_weighted_F0_excited": amp_weighted_f0,
            "T9_eff": T9_eff,
            "f_gs": p24.f_gs,
            "R_gs_T9eff": p24.R_gs(T9_eff),
            "R_ex_v21_comparison": paper24_v21,
            "formulae": {
                "q_scale_from_B_E2": "q_scale[b] = sqrt(B(E2)[e^2 fm^4]) / 100",
                "q_trans_ex_import": "q_trans_ex = q_scale * <F0>_amp,ex",
                "R_ex": "R_ex(T9) = exp[-epsilon_n * ((q_trans_ex/x)/Q_d) * nu_34(T9)]",
                "branch_sum": "R_34,tot = f_gs R_gs + (1-f_gs) R_ex",
            },
        },
        "import_cases": [asdict(case) for case in cases],
        "outcome": outcome,
        "artifacts": {
            "results_json": str(OUT_JSON),
            "memo": str(OUT_MEMO),
        },
    }
    return payload


def write_json(path: Path, payload: dict[str, Any]) -> None:
    path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def write_memo(payload: dict[str, Any]) -> None:
    sources = payload["source_values"]
    cases = {row["label"]: row for row in payload["import_cases"]}
    primary = cases[payload["outcome"]["preferred_case"]]
    up = cases["henderson_be7_published_upward_convention"]
    rejected = cases["gemini_half_factor_rejected_diagnostic"]
    v21 = payload["paper24_model_inputs"]["R_ex_v21_comparison"]
    tunl = sources["tunl_lifetime_crosscheck"]
    li = sources["lichtenstadt_tunl_mirror_crosscheck"]

    memo = f"""# Paper 24 v2.3 Excited-State Import Recalculation

Classification: `{CLASSIFICATION}`

## Verdict

Outcome: `B`, with a stable lithium conclusion.

The imported primary Henderson response does not reproduce the stated comparison value `R_ex = 0.666` as an exact central number under every convention. The corrected excited-state de-excitation convention gives:

- `R_ex(T9_eff) = {primary['R_ex_T9eff']:.9f}`
- `R_34,tot(T9_eff) = {primary['R_34_tot_T9eff']:.9f}`
- PRyMordial rerun: `Li7/H = {primary['Li7_H']:.16e}` (`{primary['Li7_sigma']:+.6f} sigma`)
- `D/H = {primary['D_H']:.16e}` (`{primary['D_H_sigma']:+.6f} sigma`)
- `Y_p = {primary['Y_p']:.16f}` (`{primary['Y_p_sigma']:+.6f} sigma`)

This means v2.3 should not say the central value is literally unchanged. It can say the primary-source excited-state response preserves the Paper 24 lithium result within the imported-source/convention band.

## Source Verification

Henderson 2019 reports `B(E2; 3/2- -> 1/2-) = 26(6)(3) e^2 fm^4`. The combined uncertainty used here is `{sources['henderson_2019']['combined_sigma']:.6f} e^2 fm^4`.

Spin-multiplicity check:

`(2J_i+1) B(i->f) = (2J_f+1) B(f->i)`.

For Henderson's published upward `3/2- -> 1/2-` value:

`B(E2; 1/2- -> 3/2-) = 2 * 26 = {sources['henderson_2019']['B_E2_down_corrected_e2fm4']:.6f} e^2 fm^4`.

The Gemini statement that the factor gives about `13 e^2 fm^4` is rejected; it uses the inverse factor.

## Computation Rule

The import rule used here replaces the v2.1 cluster-deformation scale with the measured transition response:

`q_scale[b] = sqrt(B(E2)[e^2 fm^4]) / 100`

`q_trans,ex = q_scale * <F0>_amp,ex`

where `<F0>_amp,ex = {payload['paper24_model_inputs']['amp_weighted_F0_excited']:.15f}` is the existing Paper 24 excited-branch amplitude-weighted Coulomb average.

Then:

`R_ex(T9) = exp[-epsilon_n * ((q_trans,ex/x)/Q_d) * nu_34(T9)]`

and:

`R_34,tot = f_gs R_gs + (1-f_gs) R_ex`.

## Henderson Cases

Primary excited-state de-excitation convention:

- `B(E2) = {primary['B_E2_used_e2fm4']:.6f} e^2 fm^4`
- `q_scale = {primary['q_scale_b']:.12f} b`
- `q_trans,ex = {primary['q_trans_ex_b']:.12f} b`
- `R_ex(T9_eff) = {primary['R_ex_T9eff']:.9f}`
- `R_ex(T9_eff)` 1-sigma B(E2) range = `{primary['R_ex_T9eff_from_B_plus_1sigma']:.9f}` to `{primary['R_ex_T9eff_from_B_minus_1sigma']:.9f}` (larger B gives stronger suppression)
- `Li7/H = {primary['Li7_H']:.16e}`

Published upward Coulomb-excitation convention:

- `B(E2) = {up['B_E2_used_e2fm4']:.6f} e^2 fm^4`
- `q_scale = {up['q_scale_b']:.12f} b`
- `q_trans,ex = {up['q_trans_ex_b']:.12f} b`
- `R_ex(T9_eff) = {up['R_ex_T9eff']:.9f}`
- `R_ex(T9_eff)` 1-sigma B(E2) range = `{up['R_ex_T9eff_from_B_plus_1sigma']:.9f}` to `{up['R_ex_T9eff_from_B_minus_1sigma']:.9f}` (larger B gives stronger suppression)
- `Li7/H = {up['Li7_H']:.16e}`

Rejected half-factor diagnostic:

- `B(E2) = {rejected['B_E2_used_e2fm4']:.6f} e^2 fm^4`
- `R_ex(T9_eff) = {rejected['R_ex_T9eff']:.9f}`
- `Li7/H = {rejected['Li7_H']:.16e}`
- This case is not load-bearing.

Paper 24 v2.1 comparison:

- stated comparison `R_ex = {v21['R_ex_stated_for_comparison']}`
- old amplitude-weighted `q_trans,ex = {v21['q_trans_ex_amp_weighted_b']:.12f} b`
- old-q effective `R_ex(T9_eff) = {v21['R_ex_T9eff_from_old_q_trans']:.9f}`
- old-q effective `R_34,tot(T9_eff) = {v21['R_34_tot_T9eff_from_old_q_trans']:.9f}`

The corrected Henderson de-excitation scale `q_scale={primary['q_scale_b']:.6f} b` is close to the old cluster scale `0.068 b`; this is the important physical stability check.

## Lichtenstadt / Li-7 Mirror Cross-Check

The Lichtenstadt form-factor source is a mirror diagnostic, not an independent Be-7 import without an isospin/operator assumption. The TUNL A=7 table gives the Li-7 evaluated Coulomb-excitation value:

- `B(E2; 3/2- -> 1/2-) = {TUNL_LI7_B_E2_UP:.6f} +/- {TUNL_LI7_B_E2_UP_SIGMA:.6f} e^2 fm^4`

The TUNL electron-scattering C2 gamma-width row gives:

- `Gamma_gamma0(C2) = {TUNL_LI7_C2_GAMMA_WIDTH_EV:.3e} +/- {TUNL_LI7_C2_GAMMA_WIDTH_SIGMA_EV:.3e} eV`
- inferred `B(E2 down) = {li['li7_c2_inferred_B_E2_down_e2fm4']:.6f} +/- {li['li7_c2_inferred_B_E2_down_sigma']:.6f} e^2 fm^4`
- inferred `B(E2 up) = {li['li7_c2_inferred_B_E2_up_e2fm4']:.6f} +/- {li['li7_c2_inferred_B_E2_up_sigma']:.6f} e^2 fm^4`

This is consistent with the evaluated Li-7 E2 scale within the large C2-width uncertainty. Henderson's Be/Li evaluated-up ratio is:

- `B(E2)_Be / B(E2)_Li = {li['be7_to_li7_evaluated_up_ratio']:.6f} +/- {li['be7_to_li7_evaluated_up_ratio_sigma']:.6f}`.

## TUNL Lifetime / Width Cross-Check

TUNL gives the Be-7 first excited-state lifetime:

- `tau = {TUNL_BE7_TAU_FS:.6f} +/- {TUNL_BE7_TAU_SIGMA_FS:.6f} fs`
- total width from lifetime: `{tunl['total_gamma_width_ev']:.6e} eV`
- Henderson-implied E2 partial width: `{tunl['henderson_E2_partial_width_ev']:.6e} eV`
- E2 fraction of total width: `{tunl['henderson_E2_fraction_of_total_width']:.6e}`

This confirms the lifetime is M1 dominated and cannot determine `R_ex` by itself. It is only a consistency check.

## Claim Boundary

- `verified`: Henderson numeric, spin-factor correction, TUNL lifetime, Li-7 mirror C2/evaluated-scale consistency, and PRyMordial reruns.
- `conditional`: the import rule mapping measured `B(E2)` to the Paper 24 TT branch-dressing scale.
- `not used`: Fasano 2021 and McCoy 2020 theoretical derivations as load-bearing imports.
- `not authoritative`: Odell/BRICK ANCs for this recomputation until author-verified data are received.

## References

- Henderson et al., Phys. Rev. C 99, 064320 (2019), DOI `10.1103/PhysRevC.99.064320`.
- Lichtenstadt et al., Phys. Lett. B 219, 394-398 (1989), DOI `10.1016/0370-2693(89)91083-6`.
- Tilley et al., Nucl. Phys. A 708, 3-163 (2002), DOI `10.1016/S0375-9474(02)00597-3`.
- Odell et al., Front. Phys. 10:888476 (2022), DOI `10.3389/fphy.2022.888476`.
"""
    OUT_MEMO.write_text(memo, encoding="utf-8")


def main() -> dict[str, Any]:
    payload = compute()
    write_json(OUT_JSON, payload)
    write_memo(payload)
    return payload


if __name__ == "__main__":
    print(json.dumps(main(), indent=2, sort_keys=True))
